name: Deploy Backend API Container to CloudRun
on: 
  push:
    branches:
      - develop
env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  IMAGE_NAME: asia.gcr.io/${{ secrets.GCP_PROJECT }}/kuso-app-backend
  IMAGE_TAG: ${{ github.sha }}
  SERVICE_NAME: kuso-app-backend
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: GCP Authenticate
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '273.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
      - name: Information
        run: gcloud info
      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet
      - name: Build a docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG -f ./backend/monolith/Dockerfile ./backend/monolith
      - name: Push the docker image
        run: docker push $IMAGE_NAME:$IMAGE_TAG
      - name: Deploy to Cloud Run
        run: |
            gcloud run deploy $SERVICE_NAME \
              --image $IMAGE_NAME:$IMAGE_TAG \
              --project $GCP_PROJECT \
              --region $GCP_REGION \
              --platform managed \
              --allow-unauthenticated \
              --update-env-vars=NEW_RELIC_APP_NAME=$SERVICE_NAME,NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }} \
              --quiet
