name: FrontendCIDeploy Frontend App On Develop Merge
on: 
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./front
        run: npm install
      - name: Build
        working-directory: ./front      
        run: npm run build-prod
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: front/public
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --only hosting
        env:
          PROJECT_ID: kuso-app-dev
          PROJECT_PATH: ./front
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
